# Dockerfile.frontend
# Build stage
FROM node:20.12.2 AS build

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]




