# Dockerfile for development environment
# Build stage
FROM node:20.12.2 AS build

WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client .

EXPOSE 5173

CMD [ "npm", "run", "dev" ]

