name: codexme
services:
  # Backend: Go API
  backend:
    build:
      context: .  # Assuming the Go code is under this directory
      dockerfile: Dockerfile.server  # Path to your Go Dockerfile
    ports:
      - "4000:4000"  # Expose backend on port 8080
    env_file:
      - ./server/.env
    networks:
      - codex_network

  # Nginx: Reverse Proxy
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - backend
    networks:
      - codex_network

networks:
  codex_network:
    driver: bridge


